- name: Build & Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Stopping the container
      docker_container:
        name: carvilla-container
        image: carvilla:latest
        state: stopped
    
    - name: Removing the container
      docker_container:
        name: carvilla-container
        image: carvilla:latest
        state: absent

    - name: Removing Docker image
      docker_image:
        name: carvilla:latest
        state: absent

   # - name: Copy the files to remote server
    #  shell: scp -r /var/lib/jenkins/workspace/ansible-jenkins-pipeline/ root@52.207.251.248:~/project/

    - name: Building Docker image
      docker_image:
        name: carvilla:latest
        source: build
        build:
          path: ~/project/
        state: present
 
    - name: Creating the container
      docker_container:
        name: carvilla-container
        image: carvilla:latest
        ports:
          - "80:80"
        state: started

